package com.example.lotteryapp.reusecomponent;

import android.graphics.Bitmap;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.common.BitMatrix;

/**
 * This class was generated by ChatGPT under the prompt "How to generate QR code in android studio"
 * It contains a method to return a bitmap of a QR code encoding the given text string in size-by-size
 *
 * Purpose: Return a bitmap of a QR code encoding text into size x size. Not a model
 *
 * Issues: None
 */
public class QR {
    public static Bitmap generateQrCode(String text, int size) throws WriterException {
        QRCodeWriter writer = new QRCodeWriter();
        BitMatrix bitMatrix = writer.encode(text, BarcodeFormat.QR_CODE, size, size);
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.RGB_565);

        for (int x = 0; x < size; x++) {
            for (int y = 0; y < size; y++) {
                bmp.setPixel(x, y, bitMatrix.get(x, y) ? 0xFF000000 : 0xFFFFFFFF);
            }
        }
        return bmp;
    }

}
